# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Interface(object):
    def setupUi(self, Interface):
        Interface.setObjectName("Interface")
        Interface.resize(704, 258)
        Interface.setStyleSheet("background-color: rgb(255, 255, 255);")

        self.RD_selectBox = QtWidgets.QComboBox(Interface)
        self.RD_selectBox.setGeometry(QtCore.QRect(580, 210, 101, 31))
        self.RD_selectBox.setObjectName("RD_selectBox")
        for i in range(3):
            self.RD_selectBox.addItem("")

        self.retranslateUi(Interface)
        QtCore.QMetaObject.connectSlotsByName(Interface)

    def retranslateUi(self, Interface):
        _translate = QtCore.QCoreApplication.translate
        Interface.setWindowTitle(_translate("Interface", "Dialog"))
        for i in range(3):
            self.RD_selectBox.setItemText(i, _translate("Interface", f"Line {i+1}"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Interface = QtWidgets.QDialog()
    ui = Ui_Interface()
    ui.setupUi(Interface)
    Interface.show()
    sys.exit(app.exec_())
