# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 169)
        self.leftButton = QtWidgets.QPushButton(Dialog)
        self.leftButton.setGeometry(QtCore.QRect(20, 30, 161, 51))
        self.leftButton.setObjectName("leftButton")
        self.rightButton = QtWidgets.QPushButton(Dialog)
        self.rightButton.setGeometry(QtCore.QRect(200, 30, 161, 51))
        self.rightButton.setObjectName("rightButton")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(80, 110, 211, 31))
        self.label.setText("")
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

        self.leftButton.clicked.connect(self.leftButtonClicked)
        self.rightButton.clicked.connect(self.rightButtonClicked)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.leftButton.setText(_translate("Dialog", "PushButton"))
        self.rightButton.setText(_translate("Dialog", "PushButton"))

    def leftButtonClicked(self):
        self.label.setText("left button clicked")
        self.label.setStyleSheet('color:rgb(255,0,0)')
    def rightButtonClicked(self):
        self.label.setText("right button clicked")
        self.label.setStyleSheet('color:rgb(0,200,0)')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
